spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:}

promptlayer:
  api-key: ${PROMPTLAYER_API_KEY:}
  meal-plan-id: ${MEAL_PLAN_PROMPT_ID:meal-plan}

